export const translations = {
  zh: {
    title: "与TAO一起共建新一代",
    subtitle: "AI Agent!",
    connectWallet: "连接钱包",
    connecting: "连接中...",
    selectWallet: "选择钱包",
    donate: "捐赠 USDT",
    enterAmount: "输入 USDT 金额",
    confirmDonation: "确认捐赠",
    processing: "处理中...",
    switchLanguage: "Switch to English",
    connectSuccess: "连接成功",
    walletAddress: "钱包地址",
    connectFailed: "连接失败",
    invalidAmount: "无效金额",
    enterValidAmount: "请输入有效的 USDT 金额",
    insufficientUSDT: "USDT 余额不足",
    insufficientBNB: "BNB 余额不足",
    donationSuccess: "捐赠成功",
    thankYouDonation: "感谢您捐赠 {amount} USDT",
    generalError: "发生错误，请稍后再试",
    insufficientUSDTMessage: "USDT 余额不足，请确保您有足够的 USDT",
    insufficientBNBMessage: "BNB 余额不足以支付 gas 费用，请确保您有足够的 BNB",
    userRejected: "user rejected transaction",
    userRejectedMessage: "您取消了交易",
    donationFailed: "捐赠失败",
  },
  en: {
    title: "Build the Next Generation with TAO",
    subtitle: "AI Agent!",
    connectWallet: "Connect Wallet",
    connecting: "Connecting...",
    selectWallet: "Select Wallet",
    donate: "Donate USDT",
    enterAmount: "Enter USDT Amount",
    confirmDonation: "Confirm Donation",
    processing: "Processing...",
    switchLanguage: "切换到中文",
    connectSuccess: "Connection Successful",
    walletAddress: "Wallet Address",
    connectFailed: "Connection Failed",
    invalidAmount: "Invalid Amount",
    enterValidAmount: "Please enter a valid USDT amount",
    insufficientUSDT: "Insufficient USDT balance",
    insufficientBNB: "Insufficient BNB balance",
    donationSuccess: "Donation Successful",
    thankYouDonation: "Thank you for donating {amount} USDT",
    generalError: "An error occurred, please try again later",
    insufficientUSDTMessage: "Insufficient USDT balance, please ensure you have enough USDT",
    insufficientBNBMessage: "Insufficient BNB balance for gas fees, please ensure you have enough BNB",
    userRejected: "user rejected transaction",
    userRejectedMessage: "You cancelled the transaction",
    donationFailed: "Donation Failed",
  },
}

